repos:
  - repo: local
    hooks:
      - id: gofmt
        name: go fmt
        entry: gofmt -w
        language: system
        types: [go]
      - id: staticcheck
        name: staticcheck
        entry: hack/staticcheck.sh
        language: system
        pass_filenames: false
        args: [./...]
      - id: govet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
