apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-runtime-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-runtime-operator-role
subjects:
- kind: ServiceAccount
  name: mcp-runtime-operator-controller-manager
  namespace: mcp-runtime
